Repository 8enrich/Letris, pull requests merged in 2024-09, with the labels that each got.

#63 Melhorias Visuais
  .gitignore
  AppImage/applications/letris.desktop
  AppImage/icons/hicolor/256x256/apps/letris.png
  assets/logo.png
  assets/pause.png
  assets/relaxing-bg.png
  assets/skin0.png
  assets/skin1.png
  assets/stats.png
  assets/user_settings.json
  gitignore
  include/AllocError.hpp
  include/Board.hpp
  include/Button.hpp
  include/Error.hpp
  include/Game.hpp
  include/Menu.hpp
  include/Options.hpp
  include/ScreenButton.hpp
  include/Settings.hpp
  include/Shape.hpp
  include/Vec2.hpp
  include/raylibFunctions.hpp
  src/Board.cpp
  src/Button.cpp
  src/ButtonManager.cpp
  src/Coop.cpp
  src/Game.cpp
  src/Menu.cpp
  src/Options.cpp
  src/OptionsButton.cpp
  src/Pause.cpp
  src/Screen.cpp
  src/ScreenButton.cpp
  src/ScreenManager.cpp
  src/Settings.cpp
  src/Shape.cpp
  src/main.cpp
  src/raylibFunctions.cpp
Labels: enhancement

#65 Melhorias sonoras e outras mudanças
  assets/button.wav
  assets/clear.wav
  assets/fix.wav
  assets/gameover.wav
  assets/gameplay.mp3
  assets/menu.mp3
  assets/move.wav
  assets/user_settings.json
  include/Button.hpp
  include/Game.hpp
  include/GameOver.hpp
  include/Menu.hpp
  include/Settings.hpp
  include/Stats.hpp
  src/Button.cpp
  src/ButtonManager.cpp
  src/Game.cpp
  src/GameOver.cpp
  src/Menu.cpp
  src/ScreenManager.cpp
  src/Stats.cpp
  src/main.cpp
Labels: enhancement

#69 Intro
  assets/intro.mp3
  include/Menu.hpp
  src/Menu.cpp
Labels: enhancement

#72 Tela de coopOptions finalizada
  assets/bg0.png
  assets/bg2.png
  assets/bg3.png
  assets/relaxing-bg.png
  assets/skin1.png
  assets/skin2.png
  assets/user_settings.json
  include/Board.hpp
  include/Button.hpp
  include/Coop.hpp
  include/CoopOptions.hpp
  include/Game.hpp
  include/GameOver.hpp
  include/Menu.hpp
  include/ScreenButton.hpp
  include/Settings.hpp
  include/Shape.hpp
  src/Board.cpp
  src/Button.cpp
  src/Coop.cpp
  src/CoopOptions.cpp
  src/Game.cpp
  src/ScreenButton.cpp
  src/Settings.cpp
  src/Shape.cpp
  src/main.cpp
Labels: enhancement

#73 HighLevels e adição dos scores durante a gameplay
  README.md
  assets/user_settings.json
  include/Game.hpp
  include/GameOver.hpp
  include/Settings.hpp
  src/Coop.cpp
  src/Game.cpp
  src/GameOver.cpp
  src/ScreenManager.cpp
  src/Settings.cpp
  src/Stats.cpp
Labels: enhancement

#76 Solo Options
  assets/letris.png
  assets/menubg.png
  assets/skin3.png
  include/Button.hpp
  include/CoopOptions.hpp
  include/Game.hpp
  include/GameOver.hpp
  include/Menu.hpp
  include/Settings.hpp
  include/SoloOptions.hpp
  src/Board.cpp
  src/Button.cpp
  src/Coop.cpp
  src/CoopOptions.cpp
  src/Game.cpp
  src/GameOver.cpp
  src/Menu.cpp
  src/Options.cpp
  src/ScreenManager.cpp
  src/Settings.cpp
  src/SoloOptions.cpp
  src/Stats.cpp
  src/Window.cpp
  src/main.cpp
Labels: enhancement

#79 brutal its over
  README.md
  assets/bg0.png
  assets/bg2.png
  assets/bg3.png
  assets/intro.mp3
  assets/letris.png
  assets/menubg.png
  assets/relaxing-bg.png
  assets/skin1.png
  assets/skin2.png
  assets/skin3.png
  assets/user_settings.json
  include/Board.hpp
  include/Button.hpp
  include/Coop.hpp
  include/CoopOptions.hpp
  include/Game.hpp
  include/GameOver.hpp
  include/Menu.hpp
  include/Options.hpp
  include/ScreenButton.hpp
  include/Settings.hpp
  include/Shape.hpp
  include/SoloOptions.hpp
  include/Stats.hpp
  src/Board.cpp
  src/Button.cpp
  src/Coop.cpp
  src/CoopOptions.cpp
  src/Game.cpp
  src/GameOver.cpp
  src/Menu.cpp
  src/Options.cpp
  src/ScreenButton.cpp
  src/ScreenManager.cpp
  src/Settings.cpp
  src/Shape.cpp
  src/SoloOptions.cpp
  src/Stats.cpp
  src/Window.cpp
  src/main.cpp
Labels: documentation, enhancement

#81 Consertando o erro dos controles e adicionando coisas
  include/Coop.hpp
  include/CoopOptions.hpp
  include/OptionsButton.hpp
  include/Screen.hpp
  include/SoloOptions.hpp
  src/Coop.cpp
  src/CoopOptions.cpp
  src/Game.cpp
  src/OptionsButton.cpp
  src/Screen.cpp
  src/SoloOptions.cpp
Labels: bug, enhancement
